version: "3.9"

services:
  web:
    build: /app/.
    volumes:
      - ./app/:/app/
    ports:
      - "5000:5000"
    env_file:
      - ./app/.app-env
    depends_on:
      - database
  database:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./app/data/.data-env

volumes:
  postgres_data:

