version: "3.9"

services:
  web:
    build: ./app/.
    container_name: app
    volumes:
      - ./app/:/app/
    ports:
      - "5000:5000"
    env_file:
      - ./app/.app-env
    command: python3 app.py run
    depends_on:
      - database
  database:
    image: postgres:14.5-alpine
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/data/database-schema/init-db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    env_file:
      - ./app/data/.data-env

volumes:
  postgres_data:

