apiVersion: apps/v1
kind: Deployment
metadata:
  name:  postgres
  labels:
    app:  db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1

  template:
    metadata:
      labels:
        app:  db
    spec:
      containers:
      - name:  postgres
      # that latest is not good
        image:  papp012/postgres:latest  
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_DB
          value: movie-finder
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flaskapi-secret
              key: db_root_password
        ports:
        - containerPort:  5432
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgres
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata: 
  name: postgres-svc
  labels:
    app: db
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector: 
    app: db
