apiVersion: v1
kind: PersistentVolume
metadata:
  name: movie-finder-data
  labels:
    app: movie-finder
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/mnt/data"
