apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-finder-pvc
  labels:
    app: movie-finder
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi